# Generated by Django 5.2.8 on 2025-11-11 18:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'audit")),
                ('type', models.CharField(choices=[('technical', 'Technique'), ('organizational', 'Organisationnel'), ('rgpd', 'RGPD'), ('compliance', 'Conformité')], default='technical', max_length=50, verbose_name="Type d'audit")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=50, verbose_name='Statut')),
                ('target', models.CharField(blank=True, help_text='URL, IP, domaine ou autre cible à auditer', max_length=500, null=True, verbose_name='Cible')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('score', models.IntegerField(blank=True, help_text='Score de sécurité (0-100)', null=True, verbose_name='Score')),
                ('total_findings', models.IntegerField(default=0, verbose_name='Nombre total de findings')),
                ('critical_count', models.IntegerField(default=0, verbose_name='Critiques')),
                ('high_count', models.IntegerField(default=0, verbose_name='Élevées')),
                ('medium_count', models.IntegerField(default=0, verbose_name='Moyennes')),
                ('low_count', models.IntegerField(default=0, verbose_name='Faibles')),
                ('info_count', models.IntegerField(default=0, verbose_name='Informatives')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Début')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name="Message d'erreur")),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_audits', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='tenants.tenant', verbose_name='Tenant')),
            ],
            options={
                'verbose_name': 'Audit',
                'verbose_name_plural': 'Audits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('severity', models.CharField(choices=[('critical', 'Critique'), ('high', 'Élevée'), ('medium', 'Moyenne'), ('low', 'Faible'), ('info', 'Informatif')], max_length=20, verbose_name='Sévérité')),
                ('title', models.CharField(max_length=500, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('recommendation', models.TextField(blank=True, null=True, verbose_name='Recommandation')),
                ('cwe', models.CharField(blank=True, help_text='Common Weakness Enumeration', max_length=20, null=True, verbose_name='CWE')),
                ('cvss', models.DecimalField(blank=True, decimal_places=1, help_text='Score CVSS (0.0-10.0)', max_digits=3, null=True, verbose_name='CVSS Score')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Catégorie')),
                ('priority_score', models.IntegerField(blank=True, help_text="Score calculé par l'IA (0-100)", null=True, verbose_name='Score de priorité')),
                ('ai_analyzed', models.BooleanField(default=False, verbose_name='Analysé par IA')),
                ('location', models.CharField(blank=True, help_text='URL, fichier, ligne, etc.', max_length=500, null=True, verbose_name='Localisation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='audits.audit', verbose_name='Audit')),
            ],
            options={
                'verbose_name': 'Finding',
                'verbose_name_plural': 'Findings',
                'ordering': ['-priority_score', '-cvss', 'severity', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['tenant', 'status'], name='audits_audi_tenant__b5e87a_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['tenant', 'type'], name='audits_audi_tenant__acba73_idx'),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['created_at'], name='audits_audi_created_62d5af_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['audit', 'severity'], name='audits_find_audit_i_721a85_idx'),
        ),
        migrations.AddIndex(
            model_name='finding',
            index=models.Index(fields=['priority_score'], name='audits_find_priorit_4a80b2_idx'),
        ),
    ]
